parameters:
    context.root_path: '../../../../..'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    Acme\Shared\:
        resource: '%context.root_path%/src/Shared/{Application,Domain,Infrastructure}/*'
    serializer.denormalizer.vending_machine:
        class: Acme\VendingMachine\Infrastructure\Persistence\SymfonyVendingMachineDenormalizer
        tags: [serializer.normalizer]
