parameters:
    context.root_path: '../../../../..'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    Acme\Shared\:
        resource: '%context.root_path%/src/Shared/{Application,Domain,Infrastructure}/*'
    console_command.messenger_bus:
        class: Acme\Shared\Infrastructure\Symfony\Console\Command\SymfonyMessengerBusCommand
        public: true
