parameters:
    context.root_path: '../../../../..'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Acme\Shared\Domain\Bus\Command\CommandHandler:
            tags:
                - {name: messenger.message_handler, bus: command.bus}
        Acme\Shared\Domain\Bus\Query\QueryHandler:
            tags:
                - {name: messenger.message_handler, bus: query.bus}
    Acme\Shared\:
        resource: '%context.root_path%/src/Shared/{Application,Domain,Infrastructure}/*'
